### ISSUE TITLE
Instructions Unclear

### ISSUE THREAD

**Issue by n-a-m-e** [drmargarido/linters#18]
I can't figure out how to lint a file.

The only option when hitting ctrl + shift + p is "Linter: Move To Next Warning"

Instructions say: "Make sure you have the commands needed for each linter to use them." 

If I have both linter.lua and linter_standard.lua in the plugins directory, and I have a javascript file open how do I run the linter?

**Comment by drmargarido** [comment]
Hello, the linter is run everytime you save the file.
