### ISSUE TITLE
Command not found doesn't show up in vanilla editor

### ISSUE THREAD

**Issue by mundusnine** [drmargarido/linters#19]
When we have the linter plugin installed without the console plugin we don't get feedback that the command of the plugin failed unless we look at the terminal spawned by lite on boot.

I don't know if it would be possible to show a small error message at the bottom of the window, similar to how lite shows that the file was saved:

![image](https://user-images.githubusercontent.com/29337013/103597656-c6c59880-4ece-11eb-802b-37623b3bc9f0.png)

**Comment by drmargarido** [comment]
#22 Reinforces the utility of this request.

**Comment by drmargarido** [comment]
Implemented in 17a7f7d.
