### ISSUE TITLE
Interface questions

### ISSUE THREAD

**Issue by Amantel** [drmargarido/linters#24]
A couple of UI questions: 
This issue will be about eslint, but it may concern other linters too.

1. How can I enable 'autofix on save'? That stuff is usually super handy to fix indentation
2. How can I do manual `fix`? I tried to find a command for that using ctrl+shift-p, but the fix command was missing
3. How can I list all the linter errors for the file? I see 'warnings: 4' message, but when I click on it, I see nothing.

Thanks!

**Comment by drmargarido** [comment]
1. You can add the arguments you want to the linter in your user file. Check the screenshot in the readme for an exemple with luackeck -> https://github.com/drmargarido/linters#instructions.

2. While eslint supports that, here in the linter repository we are implementing general linting for the code, not adding full support for the specific tools. So if you want to run that manually you can use the `exec` plugin, the `console` plugin or create your own plugin as I did with `gofmt`. Check https://github.com/rxi/lite-plugins.

3. Right now we have a command called `Linter: Move to Next Warning` which will jump to the next warning. If you want to use it you can bind it to a key combination in your user file. I use the following binding in my own user file:
  -> `keymap.add { ["ctrl+shift+n"] = "linter:move-to-next-warning" }`
