### ISSUE TITLE
Project wide linting creates linter lines at unexpected places

### ISSUE THREAD

**Issue by TheKing0x9** [drmargarido/linters#28]
**Describe the problem**
When using linters with a linter that does project-wide linting, linted lines turn up in files other than which contain the error/warning. 

**Steps to reproduce**
- Install linters
- modify a specific linter to lint ```.``` instead of ```$FILENAME``` 
- See the error that warning pops up in places where it should not have

**Additional Information**
- Tested on Windows
- With a custom linter designed to work with Cppcheck

**Screenshots**
```stack.c``` is the file where the error should have originally come, but it also shows up in parser.c. Same for other errors that you can see with yellow/green lines.

![Screenshot (89)](https://user-images.githubusercontent.com/33807516/122673746-8002fb00-d1ef-11eb-90fc-d8869177df37.png)
![Screenshot (88)](https://user-images.githubusercontent.com/33807516/122673751-81ccbe80-d1ef-11eb-9907-522186a8be89.png)

**Comment by drmargarido** [comment]
With the current way the linter module works it expects the linters to be used in a single file at a time.
If the tool you are using always does linting in the full project you can use the `$FILENAME` variable in the pattern to try to filter the correct file in the linter processing later. But if possible it's always preferred to pick the correct file at the beginning.

**Comment by TheKing0x9** [comment]
The problem with linting specific files is that linters don't comply with include statements then, creating warnings wherever an included function is used.

**Comment by drmargarido** [comment]
Ok, so you can use the `$FILENAME` in the pattern to filter it. In last case if the linter report is too complex a custom generator function can be used like in [linter_gocompiler](https://github.com/drmargarido/linters/blob/master/linter_gocompiler.lua)

**Comment by TheKing0x9** [comment]
Yes, that works perfectly. I wasn't aware that this could be done too :) Thanks a lot
