### ISSUE TITLE
standard

### ISSUE THREAD

**Issue by konsumer** [drmargarido/linters#7]
I am trying to make a [standardjs](https://standardjs.com/) plugin, for a PR.

I looked at the [sublime plugin](https://github.com/Flet/SublimeLinter-contrib-standard/blob/master/linter.py) for this, and translated the regex into this, in JS:

[`^  (.+):(\d+):(\d+): (.+)`](https://regex101.com/r/l8FUGm/2)

which I guess is this in lua, but it doesn't seem to pick up warnings:

```lua
local config = require "core.config"
local linter = require "plugins.linter"

config.standard_args = {}

linter.add_language {
  file_patterns = {"%.js$"},
  warning_pattern = "^  (.+):(%d+):(%d+): (.+)",
  command = "standard --verbose $ARGS $FILENAME",
  args = config.standard_args
}
```

Is my regex wrong?

**Comment by drmargarido** [comment]
In your pattern you have 4 captures, the pattern needs to have 3 capture groups, the first with the line, the second with the column and the third with the text warning.

Picking the example warning they have in the standardjs page ->
    `lib/torrent.js:950:11: Expected '===' and instead saw '=='.`

(this part can be discarded):line:col:warning
"[^:]:(%d+):(%d+): ([^\n]+)"

**Comment by konsumer** [comment]
Yep, that worked:
![Screenshot from 2020-05-10 17-18-00](https://user-images.githubusercontent.com/83857/81514152-45d3e400-92e2-11ea-9aca-ead25a6121a0.png)

Want a PR for this? I can also do one for eslint.

**Comment by konsumer** [comment]
I made one [here](https://github.com/drmargarido/linters/pull/8)
